## data
query_data_path: ./mmap/queries.mmap #revised
pos_doc_data_path: ./mmap/pos_docs.mmap
neg_doc_data_path: ./mmap/neg_docs.mmap
num_samples: 21875 #revised

## model
similarity_metric: l2
dim: 128
query_max_len: 32 #TODO
doc_max_len: 180 #TODO
mask_punctuation: true

## training
base_model: google-bert/bert-base-uncased
per_device_train_batch_size: 32
weight_decay: 0.0
lr: 3.0e-06
max_train_steps: 4000 #TODO
seed: 12345
gradient_accumulation_steps: 1
val_check_interval: 100
shuffle_train_set: false ## colbertv1 didn't shuffle
